<a href="https://colab.research.google.com/github/atwanzireT/netizen/blob/main/ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive



*   Importing pandas, numpy, matplotlib
*   Importing dataset from google colab

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
from matplotlib import pyplot as plt

In [3]:
df = pd.read_csv("/content/drive/MyDrive/coffee quality/arabica_data_cleaned.csv")
df

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.00,2200.00,2075.00
1,2,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.00,2200.00,2075.00
2,3,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.00,1800.00,1700.00
3,4,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.00,2200.00,2000.00
4,5,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.00,2200.00,2075.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,1307,Arabica,juan carlos garcia lopez,Mexico,el centenario,NaN,"la esperanza, municipio juchique de ferrer, ve...",1104328663,terra mia,900,...,None,20,"September 17th, 2013",AMECAFE,59e396ad6e22a1c22b248f958e1da2bd8af85272,0eb4ee5b3f47b20b049548a2fd1e7d4a2b70d0a7,m,900.00,900.00,900.00
1307,1308,Arabica,myriam kaplan-pasternak,Haiti,200 farms,NaN,coeb koperativ ekselsyo basen (350 members),NaN,haiti coffee,~350m,...,Blue-Green,16,"May 24th, 2013",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,350.00,350.00,350.00
1308,1309,Arabica,"exportadora atlantic, s.a.",Nicaragua,finca las marías,017-053-0211/ 017-053-0212,beneficio atlantic condega,017-053-0211/ 017-053-0212,exportadora atlantic s.a,1100,...,Green,5,"June 6th, 2018",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1100.00,1100.00,1100.00
1309,1310,Arabica,juan luis alvarado romero,Guatemala,finca el limon,NaN,beneficio serben,11/853/165,unicafe,4650,...,Green,4,"May 24th, 2013",Asociacion Nacional Del Café,b1f20fe3a819fd6b2ee0eb8fdc3da256604f1e53,724f04ad10ed31dbb9d260f0dfd221ba48be8a95,ft,1417.32,1417.32,1417.32
1310,1312,Arabica,bismarck castro,Honduras,los hicaques,103,cigrah s.a de c.v.,13-111-053,cigrah s.a de c.v,1400,...,Green,2,"April 28th, 2018",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1400.00,1400.00,1400.00

In [6]:
df.dropna()

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
29,30,Arabica,"lin, che-hao krude 林哲豪",Taiwan,tsoustructive garden 鄒築園,Tsoustructive 2015 Sumatra Typica,tsoustructive garden 鄒築園,Taiwan,taiwan coffee laboratory,1200,...,Green,0,"May 18th, 2017",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1200.0,1200.0,1200.0
115,116,Arabica,"lin, che-hao krude 林哲豪",Taiwan,shi fang yuan 十方源,2016 Tainan Coffee Cupping Event Micro Lot 臺南市...,shi fang yuan 十方源,Taiwan,taiwan coffee laboratory,350,...,Green,0,"May 18th, 2017",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,350.0,350.0,350.0
125,126,Arabica,consejo salvadoreño del café,El Salvador,monterrey,1-71,j.j. borja nathan,09-392-69,cafetalera del pacifico,1350,...,Blue-Green,2,"June 26th, 2018",Salvadoran Coffee Council,3d4987e3b91399dbb3938b5bdf53893b6ef45be1,27b21e368fb8291cbea02c60623fe6c98f84524d,m,1350.0,1350.0,1350.0
128,129,Arabica,rodrigo soto,Costa Rica,rio jorco,Tarrazu,rio jorco,5-423-0128,panamerican coffee trading,1150,...,Blue-Green,2,"October 4th, 2017",Specialty Coffee Association of Costa Rica,8e0b118f3cf3121ab27c5387deacdb7d4d2a60b1,5eb2b7129d9714c43825e44dc3bca9423de209e9,m,1150.0,1150.0,1150.0
129,130,Arabica,juan luis alvarado romero,Guatemala,san diego buena vista,11/08/0109,san diego buena vista,11/08/0109,"waelti schoenfeld exportadores de cafe, s.a.",1600,...,Green,1,"June 1st, 2017",Asociacion Nacional Del Café,b1f20fe3a819fd6b2ee0eb8fdc3da256604f1e53,724f04ad10ed31dbb9d260f0dfd221ba48be8a95,m,1600.0,1600.0,1600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,1193,Arabica,juan luis alvarado romero,Guatemala,las merceditas,11/23/0693,beneficio ixchel,11/23/0693,"unex guatemala, s.a.",1700,...,Green,1,"August 23rd, 2018",Asociacion Nacional Del Café,b1f20fe3a819fd6b2ee0eb8fdc3da256604f1e53,724f04ad10ed31dbb9d260f0dfd221ba48be8a95,m,1700.0,1700.0,1700.0
1206,1207,Arabica,"exportadora atlantic, s.a.",Nicaragua,finca las marías,017-053-0211/053-0212,beneficio atlantic condega,017-053-0211/053-0212,exportadora atlantic s.a,1100,...,Green,4,"May 22nd, 2018",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1100.0,1100.0,1100.0
1235,1236,Arabica,"lin, che-hao krude 林哲豪",Taiwan,大鋤花間 (hoe vs. flower coffee farm),2017台南市精品咖啡評鑑批次 Specialty Coffee Evaluation of...,大鋤花間 (hoe vs. flower coffee farm),Taiwan,taiwan coffee laboratory,650,...,Green,4,"June 6th, 2018",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,650.0,650.0,650.0
1253,1254,Arabica,ipanema coffees,Brazil,fazenda capoeirnha,020/17,dry mill,002/1660/0080,ipanema coffees,890,...,Green,3,"October 20th, 2018",Brazil Specialty Coffee Association,3297cfa4c538e3dd03f72cc4082c54f7999e1f9d,8900f0bf1d0b2bafe6807a73562c7677d57eb980,m,890.0,890.0,890.0
1308,1309,Arabica,"exportadora atlantic, s.a.",Nicaragua,finca las marías,017-053-0211/ 017-053-0212,beneficio atlantic condega,017-053-0211/ 017-053-0212,exportadora atlantic s.a,1100,...,Green,5,"June 6th, 2018",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1100.0,1100.0,1100.0

In [10]:
dataset = df.loc[:, ["Species", "Country.of.Origin", "Aroma", "Flavor", "Moisture", ]]

In [12]:
dataset

      Species Country.of.Origin  Aroma  Flavor  Moisture
0     Arabica          Ethiopia   8.67    8.83      0.12
1     Arabica          Ethiopia   8.75    8.67      0.12
2     Arabica         Guatemala   8.42    8.50      0.00
3     Arabica          Ethiopia   8.17    8.58      0.11
4     Arabica          Ethiopia   8.25    8.50      0.12
...       ...               ...    ...     ...       ...
1306  Arabica            Mexico   7.08    6.83      0.11
1307  Arabica             Haiti   6.75    6.58      0.14
1308  Arabica         Nicaragua   7.25    6.58      0.13
1309  Arabica         Guatemala   7.50    6.67      0.10
1310  Arabica          Honduras   0.00    0.00      0.12

[1311 rows x 5 columns]

In [15]:
dataset.describe()

             Aroma       Flavor     Moisture
count  1311.000000  1311.000000  1311.000000
mean      7.563806     7.518070     0.088863
std       0.378666     0.399979     0.047957
min       0.000000     0.000000     0.000000
25%       7.420000     7.330000     0.090000
50%       7.580000     7.580000     0.110000
75%       7.750000     7.750000     0.120000
max       8.750000     8.830000     0.280000

In [24]:
X = dataset.loc[:, ["Aroma", "Flavor"]]

In [25]:
y = dataset.loc[:, ["Moisture"]]

##Splitting Data

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [28]:
X_train.shape

(917, 2)

In [34]:
X_test.shape

(394, 2)

In [37]:
y_train.shape

(917, 1)

In [38]:
y_test.shape

(394, 1)

##Training Data

In [22]:
from sklearn.linear_model import LinearRegression

In [29]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [30]:
y_pred = regressor.predict(X_test)

In [31]:
y_pred

array([[0.09472259],
       [0.09288031],
       [0.08486799],
       [0.08574212],
       [0.08816392],
       [0.08658718],
       [0.08258864],
       [0.10136909],
       [0.08658718],
       [0.08416538],
       [0.08346277],
       [0.09138727],
       [0.09714439],
       [0.08759964],
       [0.09023235],
       [0.09309122],
       [0.08658718],
       [0.09309122],
       [0.08702425],
       [0.08509414],
       [0.08279955],
       [0.08302571],
       [0.09203524],
       [0.09066942],
       [0.08060391],
       [0.09644179],
       [0.08615012],
       [0.08623381],
       [0.09066942],
       [0.09244325],
       [0.09066942],
       [0.08486799],
       [0.07501339],
       [0.08952975],
       [0.08565842],
       [0.08909268],
       [0.09714439],
       [0.08530505],
       [0.08486799],
       [0.09401998],
       [0.09116112],
       [0.08909268],
       [0.08509414],
       [0.07946423],
       [0.08795301],
       [0.09309122],
       [0.08016684],
       [0.09159818],
       [0.11122369],
       [0.08930359],
       [0.08623381],
       [0.08702425],
       [0.07766134],
       [0.08372832],
       [0.08702425],
       [0.08509414],
       [0.08909268],
       [0.08795301],
       [0.08486799],
       [0.07787225],
       [0.09195155],
       [0.08751595],
       [0.08372832],
       [0.08346277],
       [0.08865562],
       [0.09551302],
       [0.07317111],
       [0.07637921],
       [0.08909268],
       [0.09023235],
       [0.08258864],
       [0.10849204],
       [0.09058572],
       [0.08522136],
       [0.08839007],
       [0.08323662],
       [0.08979529],
       [0.08198562],
       [0.09151448],
       [0.08710794],
       [0.08486799],
       [0.08574212],
       [0.0946389 ],
       [0.08130651],
       [0.08615012],
       [0.08416538],
       [0.08667088],
       [0.09151448],
       [0.08530505],
       [0.09014866],
       [0.08979529],
       [0.07408462],
       [0.09309122],
       [0.09195155],
       [0.09023235],
       [0.08258864],
       [0.08909268],
       [0.10764697],
       [0.09221709],
       [0.08596827],
       [0.09380907],
       [0.08930359],
       [0.09964989],
       [0.09066942],
       [0.09331738],
       [0.09401998],
       [0.08930359],
       [0.08751595],
       [0.08623381],
       [0.08865562],
       [0.09515966],
       [0.09515966],
       [0.08886653],
       [0.08460245],
       [0.09472259],
       [0.09309122],
       [0.09401998],
       [0.08574212],
       [0.09507596],
       [0.09644179],
       [0.09023235],
       [0.08865562],
       [0.10158   ],
       [0.07923808],
       [0.08395447],
       [0.09066942],
       [0.08258864],
       [0.08623381],
       [0.09265416],
       [0.08658718],
       [0.08658718],
       [0.09288031],
       [0.106999  ],
       [0.09445705],
       [0.08302571],
       [0.08060391],
       [0.08909268],
       [0.08702425],
       [0.09851022],
       [0.10294582],
       [0.08795301],
       [0.09401998],
       [0.08886653],
       [0.08236249],
       [0.08460245],
       [0.08689703],
       [0.09116112],
       [0.08165988],
       [0.08574212],
       [0.08839007],
       [0.08460245],
       [0.09195155],
       [0.09002144],
       [0.09696255],
       [0.07923808],
       [0.08888177],
       [0.09195155],
       [0.07452169],
       [0.08803671],
       [0.08667088],
       [0.08416538],
       [0.09066942],
       [0.08302571],
       [0.09644179],
       [0.08728979],
       [0.08130651],
       [0.08104097],
       [0.08615012],
       [0.09423089],
       [0.08816392],
       [0.09445705],
       [0.09401998],
       [0.07725334],
       [0.07923808],
       [0.08710794],
       [0.08979529],
       [0.08615012],
       [0.08302571],
       [0.09203524],
       [0.08751595],
       [0.08702425],
       [0.10638008],
       [0.08702425],
       [0.0897559 ],
       [0.08623381],
       [0.08623381],
       [0.09515966],
       [0.08209695],
       [0.08279955],
       [0.07725334],
       [0.09244325],
       [0.08728979],
       [0.08888177],
       [0.09309122],
       [0.09600472],
       [0.08971159],
       [0.08416538],
       [0.08865562],
       [0.09023235],
       [0.08658718],
       [0.08460245],
       [0.08795301],
       [0.08104097],
       [0.08795301],
       [0.09309122],
       [0.0831094 ],
       [0.09401998],
       [0.08979529],
       [0.08645997],
       [0.09058572],
       [0.09515966],
       [0.08323662],
       [0.09358292],
       [0.09195155],
       [0.10343752],
       [0.09023235],
       [0.07923808],
       [0.08679809],
       [0.08393923],
       [0.08909268],
       [0.07902717],
       [0.09066942],
       [0.08952975],
       [0.08104097],
       [0.08165988],
       [0.08509414],
       [0.09331738],
       [0.09066942],
       [0.08258864],
       [0.08702425],
       [0.10052402],
       [0.08909268],
       [0.08574212],
       [0.09696255],
       [0.08623381],
       [0.09151448],
       [0.08816392],
       [0.08795301],
       [0.09107742],
       [0.09244325],
       [0.09023235],
       [0.09472259],
       [0.08509414],
       [0.08486799],
       [0.10229785],
       [0.08702425],
       [0.08759964],
       [0.0946389 ],
       [0.09195155],
       [0.09401998],
       [0.08081482],
       [0.08909268],
       [0.08816392],
       [0.09472259],
       [0.08301046],
       [0.09745424],
       [0.08258864],
       [0.08865562],
       [0.08187079],
       [0.08658718],
       [0.08615012],
       [0.09066942],
       [0.09195155],
       [0.08372832],
       [0.08751595],
       [0.08574212],
       [0.08258864],
       [0.06876457],
       [0.08258864],
       [0.08658718],
       [0.09780761],
       [0.10501426],
       [0.09551302],
       [0.08658718],
       [0.09221709],
       [0.08865562],
       [0.0966527 ],
       [0.09600472],
       [0.08037775],
       [0.08553121],
       [0.09023235],
       [0.08795301],
       [0.09151448],
       [0.09066942],
       [0.08437629],
       [0.08596827],
       [0.09331738],
       [0.08909268],
       [0.10787312],
       [0.08530505],
       [0.09058572],
       [0.08658718],
       [0.08258864],
       [0.07944899],
       [0.08615012],
       [0.08574212],
       [0.08772686],
       [0.08623381],
       [0.07923808],
       [0.08702425],
       [0.08759964],
       [0.09472259],
       [0.08372832],
       [0.08909268],
       [0.08909268],
       [0.08979529],
       [0.09002144],
       [0.08615012],
       [0.08522136],
       [0.09159818],
       [0.10356474],
       [0.08816392],
       [0.08565842],
       [0.10044033],
       [0.08574212],
       [0.08931884],
       [0.09244325],
       [0.08553121],
       [0.08702425],
       [0.08839007],
       [0.09244325],
       [0.08395447],
       [0.08878283],
       [0.10387459],
       [0.08667088],
       [0.09309122],
       [0.08060391],
       [0.09023235],
       [0.09401998],
       [0.08909268],
       [0.08619443],
       [0.09058572],
       [0.09172539],
       [0.08702425],
       [0.08679809],
       [0.09116112],
       [0.09288031],
       [0.08679809],
       [0.08437629],
       [0.08486799],
       [0.08574212],
       [0.08016684],
       [0.10052402],
       [0.09107742],
       [0.08795301],
       [0.08416538],
       [0.09441274],
       [0.08667088],
       [0.08816392],
       [0.08751595],
       [0.08209695],
       [0.10052402],
       [0.09265416],
       [0.08437629],
       [0.09401998],
       [0.08574212],
       [0.09107742],
       [0.09515966],
       [0.08416538],
       [0.08795301],
       [0.08509414],
       [0.09116112],
       [0.08037775],
       [0.08302571],
       [0.10093202],
       [0.10787312],
       [0.08395447],
       [0.08702425],
       [0.08460245],
       [0.09401998],
       [0.08702425],
       [0.09335676],
       [0.09151448],
       [0.08301046],
       [0.08460245],
       [0.08165988],
       [0.08416538],
       [0.09494875],
       [0.09244325],
       [0.08209695],
       [0.09244325],
       [0.09577857],
       [0.09265416],
       [0.08346277],
       [0.09780761],
       [0.09380907],
       [0.08509414],
       [0.08623381],
       [0.08565842],
       [0.08636103],
       [0.10093202],
       [0.08574212],
       [0.08952975],
       [0.09107742]])

In [32]:
y_test

      Moisture
1120      0.15
1072      0.11
198       0.12
575       0.11
331       0.12
...        ...
323       0.10
1306      0.11
325       0.00
941       0.10
1070      0.11

[394 rows x 1 columns]


##Evaluating accuracy of a model using calculations

After you train a model, you need to get a sense of it's accuracy. The accuracy of a model gives you an idea of how much confidence you can put it predictions made by the model.

The scitkit-learn and numpy libraries are both helpful for measuring model accuracy

Let's start by recreating our trained linear regression model from the last lesson